### ISSUE TITLE
[SP5] Survey Template: Slider Image

### ISSUE THREAD

**Issue by sandysaille** [prontotools/simplesat#14]
As Pronto Tools, I want survey template for slider image so that I can have different layout of slider image.

**Note**
https://projects.invisionapp.com/share/SY7R8SHCF#/screens/179220687_Layout_Desktop
https://projects.invisionapp.com/share/SY7R8SHCF#/screens/177973907_Customer_Email_Question_-_BG_Change_-_State_1

**Exit Criteria**
- [x] Combine all components
 - [x] Question
 - [x] Previous/Skip button
 - [x] Progress Bar
 - [x] Logo
 - [x] Slider
 - [x] Image
 - [x] Slider with image
- Show Logo in template
- Have different layout in different url
 - [x] Layout 1 - Kel : Component name `SurveyLayout1`
 - [x] Layout 2 - Kid : Component name `SurveyLayout2`
 - [x] Layout 3 - Sandy : Component name `SurveyLayout3`
 - [x] Layout 4 - Oy : Component name `SurveyLayout4`
 - [x] Layout 5  - Gam : Component name `SurveyLayout5`
- Host in github (Ex: https://zkan.github.io/try-react/)
- Image Preload
 - [x] Write image preload function 
 - [x] Use compress lib to compress image files

**Tasks**
- [x] #12 Slider Base
- [x] #11 Buttons
- [x] #10 Progress Bar
- [x] #8 Slider with image
- [x] #13 Question component
- [x] #9 Image
- [x] #16 Logo

**Bonus Point**
* Be able to next question
* Progress bar works when moving to next questions

**Comment by lukyth** [comment]
In "Resize source images", I'm wondering how can we know what size each images should be. There's no telling just by reading the file alone. Some should be small, some should be large, it depends.

**Comment by zkan** [comment]
On https://simplesat.herokuapp.com/e when I hover on the previous and next buttons, the cursor doesn't change. It changes on https://simplesat.herokuapp.com/d.

Should we make it the same?

**Comment by sandysaille** [comment]
Yes, will fix it today ka.

**Comment by lukyth** [comment]
From the 'Resize source images' thing before. I think it might be possible to declare on the source code which size of the image it need and make Webpack do the works for us.

### Candidates:
- [Responsive Loader](https://github.com/herrstucki/responsive-loader)
- [Resize Image Loader](https://github.com/Levelmoney/resize-image-loader)
